version: '3'
services:
  notebook:
    build: ./notebook
    ports:
      - "8888-9000:8888-9000"
    volumes:  
      - $HOME:/home/jovyan
  databse:
    build: ./database
    ports:
     - "5432:5432"
    volumes:    
     - "$HOME:/home"
